### ISSUE TITLE
Modularize the styles

### ISSUE THREAD

**Issue by manikantag** [akveo/angular-progress-button-styles#1]
Hi, very useful module. But it would be nice to have the css styles modularized (small individual css files?). One can pick the selected styles instead of all those style. I m not sure if a single application will use all the styles anyway! Thanks

**Comment by lugovsky** [comment]
Hi! Thanks a lot for the interest in the prooject.

Actually css is modularized. Not the css itself though, but sass and less sources. Please refer to appropriate directories.

If you would like to leave some particular style, you can always build styles on your own. For example, if "fill horizontal" is the only thing you need, the you would be required to import following files:

``` sass
@import 'variables';
@import 'progress-button';
@import 'fill-horizontal';
```

The idea behind that is simple. If you don't care about optimisation and css size, you use all the styles. If you do, you build styles on your own.

**Comment by manikantag** [comment]
Good enough. Thanks
