### ISSUE TITLE
progress bar not shrinking

### ISSUE THREAD

**Issue by digitalgears** [akveo/angular-progress-button-styles#9]
missing loading-state class means the progress bar doesnt collapse

pull request here #8

**Comment by KostyaDanovsky** [comment]
Toby, sorry for the previous version. 
I have merged your pull request, thanks.

**Comment by digitalgears** [comment]
No problem. I didn't update the dist directory (I assumed you had a travis
build server or something), so this needs doing otherwise people wont see
the change

**Comment by KostyaDanovsky** [comment]
Thanks again, sorry, too much work today
